<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui/card';

	let {
		onSelectPreset
	}: {
		onSelectPreset: (preset: {
			rule_scope: 'path_prefix' | 'path_regex' | 'exact_url';
			pattern: string;
			allow_ai_edit: boolean | null;
			allow_ai_generate: boolean | null;
			allow_index: boolean | null;
			notes: string | null;
		}) => void;
	} = $props();

	const presets = [
		{
			name: 'Block AI edits on legal pages',
			description: 'Prevent AI from editing content under /legal/',
			rule_scope: 'path_prefix' as const,
			pattern: '/legal/',
			allow_ai_edit: false,
			allow_ai_generate: null,
			allow_index: null,
			notes: 'Legal content should not be modified by AI'
		},
		{
			name: 'Noindex thank you pages',
			description: 'Prevent indexing of thank you pages',
			rule_scope: 'path_prefix' as const,
			pattern: '/thank-you/',
			allow_ai_edit: null,
			allow_ai_generate: null,
			allow_index: false,
			notes: 'Thank you pages should not be indexed'
		},
		{
			name: 'Allow AI blog generation',
			description: 'Allow AI to generate blog posts under /blog/',
			rule_scope: 'path_prefix' as const,
			pattern: '/blog/',
			allow_ai_edit: null,
			allow_ai_generate: true,
			allow_index: null,
			notes: 'Blog posts can be generated by AI'
		}
	];
</script>

<div class="space-y-4">
	<h3 class="text-sm font-semibold">Quick Presets</h3>
	<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
		{#each presets as preset}
			<Card class="cursor-pointer hover:shadow-md transition-shadow" onclick={() => onSelectPreset(preset)}>
				<CardHeader class="pb-3">
					<CardTitle class="text-sm">{preset.name}</CardTitle>
					<CardDescription class="text-xs">{preset.description}</CardDescription>
				</CardHeader>
				<CardContent>
					<Button size="sm" variant="outline" class="w-full">
						Use Preset
					</Button>
				</CardContent>
			</Card>
		{/each}
	</div>
</div>
